#pragma once
// Embedded copy of db/schema_postgres.sql — kept as source-of-truth on
// disk for readability, but compiled in so the server never fails to
// start just because it was launched from a different working directory.
namespace pulse::db {
inline constexpr const char* kSchemaSql =
    "-- Pulse schema — PostgreSQL.\n"
    "-- Direct conversion from the SQLite schema this replaced: same table\n"
    "-- shapes, same column names, so application-level query logic barely\n"
    "-- changed. Differences from the SQLite version:\n"
    "--   - SERIAL/BIGSERIAL instead of INTEGER PRIMARY KEY AUTOINCREMENT\n"
    "--   - BOOLEAN instead of INTEGER 0/1 flags\n"
    "--   - BIGINT epoch-seconds kept for created_at/updated_at/etc (not\n"
    "--     TIMESTAMPTZ) specifically so no application code needs to change\n"
    "--     how it reads/writes/compares these values\n"
    "--   - tables reordered so every REFERENCES target already exists at\n"
    "--     CREATE TABLE time — Postgres validates this immediately, SQLite\n"
    "--     doesn't\n"
    "\n"
    "CREATE TABLE IF NOT EXISTS users (\n"
    "    id                   BIGSERIAL PRIMARY KEY,\n"
    "    username             TEXT NOT NULL UNIQUE,\n"
    "    password_hash        TEXT DEFAULT NULL,\n"
    "    password_salt        TEXT DEFAULT NULL,\n"
    "    google_id            TEXT DEFAULT NULL UNIQUE,\n"
    "    discord_id           TEXT DEFAULT NULL UNIQUE,\n"
    "    display_name         TEXT NOT NULL,\n"
    "    bio                  TEXT NOT NULL DEFAULT '',\n"
    "    pronouns             TEXT NOT NULL DEFAULT '',\n"
    "    status_text          TEXT NOT NULL DEFAULT '',\n"
    "    avatar_url           TEXT NOT NULL DEFAULT '',\n"
    "    banner_url           TEXT NOT NULL DEFAULT '',\n"
    "    accent_color_top     TEXT NOT NULL DEFAULT '#5865F2',\n"
    "    accent_color_bottom  TEXT NOT NULL DEFAULT '#EB459E',\n"
    "    theme_json           TEXT NOT NULL DEFAULT '{}',\n"
    "    created_at           BIGINT NOT NULL\n"
    ");\n"
    "\n"
    "CREATE TABLE IF NOT EXISTS servers (\n"
    "    id                   BIGSERIAL PRIMARY KEY,\n"
    "    name                 TEXT NOT NULL,\n"
    "    icon_url             TEXT NOT NULL DEFAULT '',\n"
    "    accent_color_top     TEXT NOT NULL DEFAULT '#5865F2',\n"
    "    accent_color_bottom  TEXT NOT NULL DEFAULT '#EB459E',\n"
    "    owner_id             BIGINT NOT NULL REFERENCES users(id),\n"
    "    invite_code          TEXT NOT NULL UNIQUE,\n"
    "    created_at           BIGINT NOT NULL\n"
    ");\n"
    "\n"
    "CREATE TABLE IF NOT EXISTS server_members (\n"
    "    server_id  BIGINT NOT NULL REFERENCES servers(id),\n"
    "    user_id    BIGINT NOT NULL REFERENCES users(id),\n"
    "    role       TEXT NOT NULL DEFAULT 'member', -- 'owner' | 'admin' | 'member'\n"
    "    joined_at  BIGINT NOT NULL,\n"
    "    PRIMARY KEY (server_id, user_id)\n"
    ");\n"
    "\n"
    "CREATE TABLE IF NOT EXISTS dm_channels (\n"
    "    id         BIGSERIAL PRIMARY KEY,\n"
    "    is_group   BOOLEAN NOT NULL DEFAULT FALSE,\n"
    "    name       TEXT NOT NULL DEFAULT '',\n"
    "    server_id  BIGINT DEFAULT NULL REFERENCES servers(id),\n"
    "    topic      TEXT NOT NULL DEFAULT '',\n"
    "    position   INTEGER NOT NULL DEFAULT 0,\n"
    "    created_at BIGINT NOT NULL\n"
    ");\n"
    "\n"
    "CREATE TABLE IF NOT EXISTS dm_members (\n"
    "    channel_id BIGINT NOT NULL REFERENCES dm_channels(id),\n"
    "    user_id    BIGINT NOT NULL REFERENCES users(id),\n"
    "    joined_at  BIGINT NOT NULL,\n"
    "    PRIMARY KEY (channel_id, user_id)\n"
    ");\n"
    "\n"
    "CREATE TABLE IF NOT EXISTS messages (\n"
    "    id              BIGSERIAL PRIMARY KEY,\n"
    "    channel_id      BIGINT NOT NULL REFERENCES dm_channels(id),\n"
    "    sender_id       BIGINT NOT NULL REFERENCES users(id),\n"
    "    body_raw        TEXT NOT NULL,\n"
    "    body_rendered   TEXT NOT NULL,\n"
    "    reply_to_id     BIGINT DEFAULT NULL REFERENCES messages(id),\n"
    "    edited_at       BIGINT DEFAULT NULL,\n"
    "    deleted         BOOLEAN NOT NULL DEFAULT FALSE,\n"
    "    created_at      BIGINT NOT NULL\n"
    ");\n"
    "\n"
    "CREATE TABLE IF NOT EXISTS message_reactions (\n"
    "    message_id BIGINT NOT NULL REFERENCES messages(id),\n"
    "    user_id    BIGINT NOT NULL REFERENCES users(id),\n"
    "    emoji      TEXT NOT NULL,\n"
    "    PRIMARY KEY (message_id, user_id, emoji)\n"
    ");\n"
    "\n"
    "CREATE TABLE IF NOT EXISTS read_receipts (\n"
    "    channel_id            BIGINT NOT NULL REFERENCES dm_channels(id),\n"
    "    user_id               BIGINT NOT NULL REFERENCES users(id),\n"
    "    last_read_message_id  BIGINT NOT NULL DEFAULT 0,\n"
    "    updated_at            BIGINT NOT NULL,\n"
    "    PRIMARY KEY (channel_id, user_id)\n"
    ");\n"
    "\n"
    "CREATE TABLE IF NOT EXISTS posts (\n"
    "    id            BIGSERIAL PRIMARY KEY,\n"
    "    author_id     BIGINT NOT NULL REFERENCES users(id),\n"
    "    body_raw      TEXT NOT NULL,\n"
    "    body_rendered TEXT NOT NULL,\n"
    "    media_url     TEXT NOT NULL DEFAULT '',\n"
    "    created_at    BIGINT NOT NULL\n"
    ");\n"
    "\n"
    "CREATE TABLE IF NOT EXISTS post_comments (\n"
    "    id            BIGSERIAL PRIMARY KEY,\n"
    "    post_id       BIGINT NOT NULL REFERENCES posts(id),\n"
    "    author_id     BIGINT NOT NULL REFERENCES users(id),\n"
    "    body_raw      TEXT NOT NULL,\n"
    "    body_rendered TEXT NOT NULL,\n"
    "    created_at    BIGINT NOT NULL\n"
    ");\n"
    "\n"
    "CREATE TABLE IF NOT EXISTS post_reactions (\n"
    "    post_id    BIGINT NOT NULL REFERENCES posts(id),\n"
    "    user_id    BIGINT NOT NULL REFERENCES users(id),\n"
    "    emoji      TEXT NOT NULL,\n"
    "    created_at BIGINT NOT NULL,\n"
    "    PRIMARY KEY (post_id, user_id, emoji)\n"
    ");\n"
    "\n"
    "CREATE TABLE IF NOT EXISTS media (\n"
    "    id          TEXT PRIMARY KEY,\n"
    "    owner_id    BIGINT NOT NULL REFERENCES users(id),\n"
    "    mime_type   TEXT NOT NULL,\n"
    "    byte_size   BIGINT NOT NULL,\n"
    "    created_at  BIGINT NOT NULL\n"
    ");\n"
    "\n"
    "CREATE TABLE IF NOT EXISTS notifications (\n"
    "    id             BIGSERIAL PRIMARY KEY,\n"
    "    user_id        BIGINT NOT NULL REFERENCES users(id), -- recipient\n"
    "    type           TEXT NOT NULL, -- 'message' | 'reaction' | 'comment' | 'server_invite'\n"
    "    actor_id       BIGINT REFERENCES users(id),           -- who caused it\n"
    "    actor_username TEXT NOT NULL DEFAULT '',\n"
    "    channel_id     BIGINT DEFAULT NULL,\n"
    "    post_id        BIGINT DEFAULT NULL,\n"
    "    body           TEXT NOT NULL DEFAULT '',\n"
    "    read           BOOLEAN NOT NULL DEFAULT FALSE,\n"
    "    created_at     BIGINT NOT NULL\n"
    ");\n"
    "\n"
    "CREATE INDEX IF NOT EXISTS idx_posts_created ON posts(created_at);\n"
    "CREATE INDEX IF NOT EXISTS idx_comments_post ON post_comments(post_id, created_at);\n"
    "CREATE INDEX IF NOT EXISTS idx_messages_channel ON messages(channel_id, created_at);\n"
    "CREATE INDEX IF NOT EXISTS idx_channels_server ON dm_channels(server_id, position);\n"
    "CREATE INDEX IF NOT EXISTS idx_server_members_user ON server_members(user_id);\n"
    "CREATE INDEX IF NOT EXISTS idx_notifications_user ON notifications(user_id, read, created_at);\n"
    "";
} // namespace pulse::db
