#pragma once
// Embedded copy of db/schema.sql — kept as source-of-truth on disk for
// readability, but compiled in so the server never fails to start just
// because it was launched from a different working directory.
namespace pulse::db {
inline constexpr const char* kSchemaSql =
    "-- Phase 1 schema (SQLite). Migrates to Postgres in Phase 2 with the same\n"
    "-- shape, so application code barely changes.\n"
    "\n"
    "CREATE TABLE IF NOT EXISTS users (\n"
    "    id            INTEGER PRIMARY KEY AUTOINCREMENT,\n"
    "    username      TEXT NOT NULL UNIQUE,\n"
    "    password_hash TEXT NOT NULL,\n"
    "    password_salt TEXT NOT NULL,\n"
    "    display_name  TEXT NOT NULL,\n"
    "    bio           TEXT DEFAULT '',\n"
    "    pronouns      TEXT DEFAULT '',\n"
    "    status_text   TEXT DEFAULT '',\n"
    "    avatar_url    TEXT DEFAULT '',\n"
    "    banner_url    TEXT DEFAULT '',\n"
    "    accent_color_top    TEXT DEFAULT '#5865F2',\n"
    "    accent_color_bottom TEXT DEFAULT '#EB459E',\n"
    "    theme_json    TEXT DEFAULT '{}',\n"
    "    created_at    INTEGER NOT NULL\n"
    ");\n"
    "\n"
    "CREATE TABLE IF NOT EXISTS posts (\n"
    "    id            INTEGER PRIMARY KEY AUTOINCREMENT,\n"
    "    author_id     INTEGER NOT NULL REFERENCES users(id),\n"
    "    body_raw      TEXT NOT NULL,\n"
    "    body_rendered TEXT NOT NULL,\n"
    "    created_at    INTEGER NOT NULL\n"
    ");\n"
    "\n"
    "CREATE TABLE IF NOT EXISTS post_comments (\n"
    "    id            INTEGER PRIMARY KEY AUTOINCREMENT,\n"
    "    post_id       INTEGER NOT NULL REFERENCES posts(id),\n"
    "    author_id     INTEGER NOT NULL REFERENCES users(id),\n"
    "    body_raw      TEXT NOT NULL,\n"
    "    body_rendered TEXT NOT NULL,\n"
    "    created_at    INTEGER NOT NULL\n"
    ");\n"
    "\n"
    "CREATE TABLE IF NOT EXISTS post_reactions (\n"
    "    post_id    INTEGER NOT NULL REFERENCES posts(id),\n"
    "    user_id    INTEGER NOT NULL REFERENCES users(id),\n"
    "    emoji      TEXT NOT NULL,\n"
    "    created_at INTEGER NOT NULL,\n"
    "    PRIMARY KEY (post_id, user_id, emoji)\n"
    ");\n"
    "\n"
    "CREATE INDEX IF NOT EXISTS idx_posts_created ON posts(created_at);\n"
    "CREATE INDEX IF NOT EXISTS idx_comments_post ON post_comments(post_id, created_at);\n"
    "\n"
    "CREATE TABLE IF NOT EXISTS dm_channels (\n"
    "    id         INTEGER PRIMARY KEY AUTOINCREMENT,\n"
    "    is_group   INTEGER NOT NULL DEFAULT 0,\n"
    "    name       TEXT DEFAULT '',\n"
    "    created_at INTEGER NOT NULL\n"
    ");\n"
    "\n"
    "CREATE TABLE IF NOT EXISTS dm_members (\n"
    "    channel_id INTEGER NOT NULL REFERENCES dm_channels(id),\n"
    "    user_id    INTEGER NOT NULL REFERENCES users(id),\n"
    "    joined_at  INTEGER NOT NULL,\n"
    "    PRIMARY KEY (channel_id, user_id)\n"
    ");\n"
    "\n"
    "CREATE TABLE IF NOT EXISTS messages (\n"
    "    id              INTEGER PRIMARY KEY AUTOINCREMENT,\n"
    "    channel_id      INTEGER NOT NULL REFERENCES dm_channels(id),\n"
    "    sender_id       INTEGER NOT NULL REFERENCES users(id),\n"
    "    body_raw        TEXT NOT NULL,\n"
    "    body_rendered   TEXT NOT NULL,\n"
    "    created_at      INTEGER NOT NULL\n"
    ");\n"
    "\n"
    "CREATE TABLE IF NOT EXISTS message_reactions (\n"
    "    message_id INTEGER NOT NULL REFERENCES messages(id),\n"
    "    user_id    INTEGER NOT NULL REFERENCES users(id),\n"
    "    emoji      TEXT NOT NULL,\n"
    "    PRIMARY KEY (message_id, user_id, emoji)\n"
    ");\n"
    "\n"
    "CREATE INDEX IF NOT EXISTS idx_messages_channel ON messages(channel_id, created_at);\n"
    "";
} // namespace pulse::db
